spring.application.name=ModelDeck

# Gemini API
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.8-flash

# OpenRouter API
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api/v1
# Replaced with a valid OpenRouter free model:
spring.ai.openai.chat.options.model=meta-llama/llama-3-8b-instruct:free
spring.ai.openai.chat.options.max-tokens=2000

# Ollama (Will still return 500 in the cloud without an ngrok tunnel)
spring.ai.ollama.chat.options.model=llama3.2:1b